###
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "stefan123",
  "password": "12sadasd3",
  "email": "emasdasail@test.com"
}
###
PATCH http://localhost:8080/users/2
Content-Type: application/json

{
  "name": "costam",
  "surname": "ACDC",
  "movies": [{
    "id": 3
  }],
  "tvSeries": [{
    "id": 3
  }],
  "vodPlatforms": [{
    "id": 1
  }],
  "region": {
    "id": 2
  }
}

###
GET http://localhost:8080/users

###
GET http://localhost:8080/users/1

###
DELETE http://localhost:8080/users/2





###
POST http://localhost:8080/movies/add
Content-Type: application/json

{
  "title": "filmABC",
  "overview": "askljdhlaskhd",
  "releaseDate": "23/01/2020"
}

###
GET http://localhost:8080/movies

###
GET http://localhost:8080/movies/2

###
PATCH http://localhost:8080/movies/2
Content-Type: application/json

{
  "title": "ASDFG",
  "runtime": "2H"
}

###
DELETE http://localhost:8080/movies/2




###
POST http://localhost:8080/regions/add
Content-Type: application/json

{
  "city": "Paris",
  "country": "FR"
}

###
GET http://localhost:8080/regions

###
GET http://localhost:8080/regions/3

###
PATCH http://localhost:8080/regions/3
Content-Type: application/json

{
  "city": "AAAAA",
  "flag": "Flag"
}

###
DELETE http://localhost:8080/regions/3





###
POST http://localhost:8080/tvseries/add
Content-Type: application/json

{
  "name": "serie123",
  "description": "akdjslhaads",
  "adult": true
}

###
GET http://localhost:8080/tvseries

###
GET http://localhost:8080/tvseries/3

###
PATCH http://localhost:8080/tvseries/3
Content-Type: application/json

{
  "name": "ZZZZZZZZZZ"
}

###
DELETE http://localhost:8080/tvseries/3









###
POST http://localhost:8080/vodplatforms/add
Content-Type: application/json

{
  "name": "VOD123",
  "logoPath": "THISISLOGO",
  "vodURL": "URL",
  "active": false
}

###
GET http://localhost:8080/vodplatforms

###
GET http://localhost:8080/vodplatforms/2

###
PATCH http://localhost:8080/vodplatforms/2
Content-Type: application/json

{
  "name": "NOOOOOOOOOOOOOOO",
  "vodURL": "TOJESTURL",
  "active": true
}

###
DELETE http://localhost:8080/vodplatforms/2