###
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "Bob",
  "password": "qwerty",
  "email": "dywan@mail.com"
}

###
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "Jason",
  "password": "qwerty",
  "email": "domofon@mail.com"
}

###
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "Uma",
  "password": "qwerty",
  "email": "furman@mail.com"
}


###
PATCH http://localhost:8080/users/2
Content-Type: application/json

{
  "name": "Jason",
  "surname": "Domofon",
  "movies": [
    {
      "id": 1
    }
  ],
  "tvSeries": [
    {
      "id": 3
    }
  ],
  "vodPlatforms": [
    {
      "id": 1
    }
  ],
  "region": {
    "id": 2
  }
}

###
GET http://localhost:8080/users

###
GET http://localhost:8080/users/2

###
DELETE http://localhost:8080/users/2





###
POST http://localhost:8080/movies/add
Content-Type: application/json

{
  "title": "Gone with a windmills",
  "overview": "Some windmills",
  "releaseDate": "23/01/2020"
}

###
POST http://localhost:8080/movies/add
Content-Type: application/json

{
  "title": "No Title",
  "overview": "Just no title",
  "releaseDate": "23/01/2020"
}

###
POST http://localhost:8080/movies/add
Content-Type: application/json

{
  "title": "Martix",
  "overview": "kjhgf",
  "releaseDate": "23/01/2020"
}

###
GET http://localhost:8080/movies

###
GET http://localhost:8080/movies/3

###
PATCH http://localhost:8080/movies/3
Content-Type: application/json

{
  "title": "Matrix",
  "runtime": "2H"
}

###
DELETE http://localhost:8080/movies/2




###
POST http://localhost:8080/regions/add
Content-Type: application/json

{
  "city": "Paris",
  "country": "FR"
}

###
POST http://localhost:8080/regions/add
Content-Type: application/json

{
  "city": "London",
  "country": "GB"
}

###
POST http://localhost:8080/regions/add
Content-Type: application/json

{
  "city": "New Work",
  "country": "US"
}

###
GET http://localhost:8080/regions

###
GET http://localhost:8080/regions/3

###
PATCH http://localhost:8080/regions/3
Content-Type: application/json

{
  "city": "New York",
  "flag": "Flag"
}
###
PATCH http://localhost:8080/regions/1
Content-Type: application/json

{
  "city": "Paris",
  "flag": "WhiteFlag"
}

###
DELETE http://localhost:8080/regions/3





###
POST http://localhost:8080/tvseries/add
Content-Type: application/json

{
  "title": "Lucifer",
  "description": "afjhd",
  "adult": false
}

###
POST http://localhost:8080/tvseries/add
Content-Type: application/json

{
  "title": "Arcane",
  "description": "zxcvv",
  "adult": false
}

###
POST http://localhost:8080/tvseries/add
Content-Type: application/json

{
  "title": "House MD",
  "description": "hhhhhh",
  "adult": false
}

###
POST http://localhost:8080/tvseries/add
Content-Type: application/json

{
  "title": "Terminal List",
  "description": "CAUTION, creation adds vodPlatforms 1 and 2 AND region 1",
  "adult": false,
  "genre": "action",
  "poster": "poster.png",
  "origin": "data file",
  "firstAirDate": "2022-01-22",
  "lastAirDate": "2022-01-23",
  "seasons": 1,
  "episodes": 7,
  "vodPlatforms": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ],
  "apiID": 19283,
  "region": {
    "id": 1
  }
}

###
GET http://localhost:8080/tvseries

###
GET http://localhost:8080/tvseries/3

###
PATCH http://localhost:8080/tvseries/3
Content-Type: application/json

{
  "vodPlatforms": [
    {
      "id": 2
    },
    {
      "id": 1
    }
  ]
}

###
DELETE http://localhost:8080/tvseries/3










###
POST http://localhost:8080/vodplatforms/add
Content-Type: application/json

{
  "name": "Disney",
  "logoPath": "dis dis",
  "vodURL": "URL",
  "active": true
}

###
POST http://localhost:8080/vodplatforms/add
Content-Type: application/json

{
  "name": "HBO",
  "logoPath": "oOoooOoo",
  "vodURL": "URL",
  "active": false
}

###
POST http://localhost:8080/vodplatforms/add
Content-Type: application/json

{
  "name": "Netflix",
  "logoPath": "nooo",
  "vodURL": "URL",
  "active": true
}

###
GET http://localhost:8080/vodplatforms

###
GET http://localhost:8080/vodplatforms/2

###
PATCH http://localhost:8080/vodplatforms/2
Content-Type: application/json

{
  "vodURL": "TOJESTURL",
  "active": false
}

###
DELETE http://localhost:8080/vodplatforms/2